services:
  # 1. Backend API Service (.NET 9 + Docker + Neon PostgreSQL)
  - type: web
    name: leads-management-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__PostgreSqlConnection
        value: Host=ep-bitter-smoke-b3m1hg9u-pooler.c-4.ap-southeast-1.aws.neon.tech;Port=5432;Database=neondb;Username=neondb_owner;Password=npg_FzriwB8AoQ0X;SSL Mode=Require;Trust Server Certificate=true;

  # 2. Frontend React Client (Static Site on Free Global CDN)
  - type: web
    name: leads-management-web
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    rootDir: frontend
    plan: free
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
